apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
stringData:
  BucketInfo.json: |
    {
      "spec": {
        "bucketName": "test",
        "authenticationType": "Key",
        "protocols": ["S3"],
        "secretS3": {
          "endpoint": "play.min.io",
          "region": "us-east-1",
          "accessKeyID": "Q3AM3UQ867SPQQA43P2F",
          "accessSecretKey": "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
        },
        "secretAzure": null
      }
    }
